### ISSUE TITLE
Error running script

### ISSUE THREAD

**Issue by slebreton79** [nickrod518/Create-EXEFromPS1#10]

**Comment by slebreton79** [comment]
I get this error when running the script

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\Sheldon\OneDrive\Documents\WindowsPowerShell\Modules\Create-EXEFromPS1\Public\New-EXEFromPS1.ps1:456 char:9
+         Start-Process $IExpress "/N $SED" -Wait -Verb RunAs
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by nickrod518** [comment]
Hello, your Windows is missing the IExpress executable which the script expects to exist at either `C:\WINDOWS\SysWOW64\iexpress` or `C:\WINDOWS\System32\iexpress`. I hope this helps. This is outside the scope of which I'm willing to help troubleshoot.

**Comment by slebreton79** [comment]
Ah okay that makes sense
