### ISSUE TITLE
IExpress Wizard "Error opening the MakeCab Directive File"

### ISSUE THREAD

**Issue by cwmoriarty** [nickrod518/Create-EXEFromPS1#5]
I am prompted with the above error, regardless of if I specify x64 or not. Powershell ISE running as Administrator on Server 2012R2.

**Comment by cwmoriarty** [comment]
I figured this out, it appears the script needs write access to the folder as it prepares the iexpress file.

**Comment by nickrod518** [comment]
Ah, nice find.

**Comment by suditvr** [comment]
Running as admin does not work.
